### ISSUE TITLE
Screenshot 

### ISSUE THREAD

**Issue by Archo21** [Archo21/E-commerceBackEnd#1]
<img width="1792" alt="Screen Shot 2022-03-08 at 1 22 52 PM" src="https://user-images.githubusercontent.com/87740574/157327825-1d490609-a2f2-4616-b1fb-a67fb923e74d.png">
<img width="1792" alt="Screen Shot 2022-03-08 at 1 23 29 PM" src="https://user-images.githubusercontent.com/87740574/157327853-0eee8d7a-8977-4076-8d51-cc5570bcac59.png">
<img width="1792" alt="Screen Shot 2022-03-08 at 1 23 10 PM" src="https://user-images.githubusercontent.com/87740574/157327862-186825d9-2d4e-4e25-80e8-d232d861cdba.png">

**Comment by Archils** [comment]
APIs
